### ISSUE TITLE
Classification consensus sequence file.

### ISSUE THREAD

**Issue by thierryjanssens** [ejongepier/NanoClass#2]
Hi,

I am conducting metabarcoding on  eukaryotic marker genes (e.g. nuclear rRNA clusters and mitochondrial genes).
Threfore, I understand that I have to get my sequence databases of interest in place in the correct directory.

However, I would like to compare the classified reads (clusters) directly as well to the respective databases.

Where can I find the consensus sequence per OTU? Or is the classification of the reads only basedon matches with the respective databases?

kind regards,

T.

**Comment by ejongepier** [comment]
Hi T,

The use of custom databases has not been tested exhaustively but [this](https://ejongepier.github.io/NanoClass/databases.html) documentation should give you some handles on how to prepare and use them.

Note thought that NanoClass was developed to compare tools and samples, not so much databases. If you like to compare databases and generate a report including the results from both databases you need to jump some hoops.

For your workflow, I recommend:

1. Prep the first database and store it in the db/common subdirectory following [these](https://ejongepier.github.io/NanoClass/databases.html) instructions.
2. List your samples in the samples.csv and give all the same runID, e.g. "DB1"
3. Change the methods in the config.yaml such that it only lists the tools that are supported with custom databases (e.g. ["megablast", "minimap"].
4. Run NanoClass: `snakemake --use-conda --cores <ncores>`
5. **IMPORTANT** Prep the second database and change the time stamp such that the DB2-seqs.fna and DB2-taxonomy.txt are older than the results from run "DB1". This is important because if NanoClass detects a database that was changed more recently than the results that are based on it, it will rerun those analyses and overwrite the results. For you this would mean that the original DB1 results will be overwritten with the DB2 results, and you end up with two DB2-based annotations, one for run "DB1" and one for run "DB2". You can change the timestamp like so: `touch /path/to/DB2-seqs.fna -r db/common/ref-seqs.fna` and `touch /path/to/db2-taxonomy.txt -r db/common/ref-taxonomy.txt`. Only then move the db2 files to db/common/: `mv  /path/to/DB2-ref-seqs.fna db/common/ref-seqs.fna` and `mv /path/to/DB2-taxonomy.txt db/common/ref-taxonomy.txt` (i.e. replace the first db).
6. Add your samples to the existing samples.csv using the same sampleIDs as for run "DB1", but give them a different run ID, e.g. "DB2". Thus, each sample should be listed twice now, once with runID "DB1" and once with runID "DB2".
7. Check whether NanoClass would indeed only create run "DB2" output, not run "DB1" again, using the snakemake dry run option -n: `snakemake -n --use-conda --cores 1`. This will list which steps of the pipeline will be run once you start. Naturally, it should only list steps involving runID "DB2".
7. Run NanoClass again: `snakemake --use-conda --cores <ncores>`
8. Generate a report: `snakemake --report report/NanoClass.zip`. This should give taxonomic barplots for each sample, run and tool for comparison.
9. Check out / compare the taxonomic classifications per read in classifications/runID/method/sampleID-method.taxlist

Three more things:

1. Clustering / denoising does not work well on MinION amplicon sequences because of the high error rates. Therefore, each read is separately classified. For the barplots, reads are clustered based on the taxonomic classification (i.e. aggregated after running the classification, rather than clustered / denoised before, as is customary for short reads).
2. Consensus classification across different methods/tools is currently not implemented in combination with custom databases. This step is automatically skipped if you specify <3 methods in the config.yaml. If you specify 3 or more you will need to disable consensus calling across tools or you will run into an error. A quick fix is to replace line 32 in the Snakefile with `optrules.extend(["plots/precision.pdf"] if len(config["methods"]) > 200 else [])`
3. Mind that if you subsample your data, run "DB1" and run "DB2" may annotate different subsets of your reads, so better to disable subsampling in the config.yaml.

Hope this helps.

Best,
Evelien

**Comment by thierryjanssens** [comment]
Dear Evelien,

thank you for your elaborate and quick reply.
I understand this is also the way to go when different databases are deployed in consecutive analyses?

Kind regards,

Thierry

**Comment by ejongepier** [comment]
Hi Thierry,

If you do not want to compare the results using different databases, the easiest and safest solution is to just use different NanoClass instances. So for each database, just clone or copy NanoClass from github, prepare the custom database following [these](https://ejongepier.github.io/NanoClass/databases.html) instructions and run NanoClass.

If you insist using the same NanoClass instance, e.g. because you do not want to install dependencies again, follow step 1 to 4 and 8 and 9 for each database. Just make sure to remove the sample/runID for the first database from the samples.csv before you repeat the process for the second db, otherwise the first results will be overwritten.

Best,
Evelien

**Comment by thierryjanssens** [comment]
I understand.
Snakemake is executed relative to the path of the Snakefile.
Two instances of Nanoclass can coexist in this way.

Thank you for your help.

Thierry
